### ISSUE TITLE
Integrate DQA pipeline with CWL

### ISSUE THREAD

**Issue by vemonet** [MaastrichtU-IDS/d2s-cwl-workflows#1]
I started a CWL workflow for the DQA pipeline here: https://github.com/MaastrichtU-IDS/d2s-cwl-workflows/blob/master/workflows/workflow-dqa.cwl

With a config file to test it on a small graph (hgnc) that I loaded in test-dqa : https://github.com/MaastrichtU-IDS/d2s-cwl-workflows/blob/master/support/config-cwl-dqa.yml

There is only the first step at the moment (compute HCLS statistics for a provided graph URI)

The 2 first commands are to create the workspace directories (on Ubuntu). The last command is to run the workflow from the root of the GitHub repository https://github.com/MaastrichtU-IDS/d2s-cwl-workflows (after cloning it)

```bash
mkdir -p /data/dqa-workspace/output/tmp-outdir
sudo chown -R ${USER}:${USER} /data/dqa-workspace

git clone https://github.com/MaastrichtU-IDS/d2s-cwl-workflows
cd d2s-cwl-workflows

cwl-runner \
  --outdir /data/dqa-workspace/output \
  --tmp-outdir-prefix=/data/dqa-workspace/output/tmp-outdir/ \
  --tmpdir-prefix=/data/dqa-workspace/output/tmp-outdir/tmp- \
  workflows/workflow-dqa.cwl \
  support/config-cwl-dqa.yml
```

It generates metadata for the https://w3id.org/data2services/graph/biolink/hgnc graph in the https://w3id.org/data2services/graph/biolink/hgnc/metadata graph

See the test-dqa repository at http://graphdb.dumontierlab.com/graphs

Next step will be to create a CWL tool for fairsharing and RDFUnit, and add them to the pipeline

**Comment by vemonet** [comment]
Issue when running RdfUnit:

```
docker \
    run \
    -i \
    --volume=/data/dqa-workspace/output/tmp-outdir/RR6c3A:/data:rw \
    --volume=/data/dqa-workspace/output/tmp-outdir/tmp-pwkAPb:/tmp:rw \
    --workdir=/data \
    --read-only=true \
    --log-driver=none \
    --user=1000:1000 \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/data \
    umids/rdfunit:latest \
    -d \
    http://sparql.wikipathways.org/ \
    -f \
    /data/ \
    -s \
    https://www.w3.org/2012/pyRdfa/extract?uri=http://vocabularies.wikipathways.org/wp# \
    -o \
    ttl > /data/dqa-workspace/output/tmp-outdir/RR6c3A/logs-rdfunit.txt
[job step2-run-rdfunit] Job error:
Error collecting output for parameter 'rdfunit_rdf_output':
steps/run-rdfunit.cwl:45:7: Did not find output file with glob pattern: '['results']'
[job step2-run-rdfunit] completed permanentFail
[step step2-run-rdfunit] Output is missing expected field file:///home/vemonet/develop/d2s-transform-template/d2s-cwl-workflows/workflows/workflow-dqa.cwl#step2-run-rdfunit/rdfunit_rdf_output
[step step2-run-rdfunit] Output is missing expected field file:///home/vemonet/develop/d2s-transform-template/d2s-cwl-workflows/workflows/workflow-dqa.cwl#step2-run-rdfunit/rdfunit_logs
```

Output in logs-rdfunit.txt
```
First run, compiling code...
[[1;34mINFO[m] Scanning for projects...
[[1;31mERROR[m] [ERROR] Could not find the selected project in the reactor: rdfunit-validate @ 
[[1;31mERROR[m] Could not find the selected project in the reactor: rdfunit-validate -> [1m[Help 1][m
[[1;31mERROR[m] 
[[1;31mERROR[m] To see the full stack trace of the errors, re-run Maven with the [1m-e[m switch.
[[1;31mERROR[m] Re-run Maven using the [1m-X[m switch to enable full debug logging.
[[1;31mERROR[m] 
[[1;31mERROR[m] For more information about the errors and possible solutions, please read the following articles:
[[1;31mERROR[m] [1m[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
Compiling finished...
[[1;31mERROR[m] [ERROR] Could not find the selected project in the reactor: rdfunit-validate @ 
[[1;31mERROR[m] Could not find the selected project in the reactor: rdfunit-validate -> [1m[Help 1][m
[[1;31mERROR[m] 
[[1;31mERROR[m] To see the full stack trace of the errors, re-run Maven with the [1m-e[m switch.
[[1;31mERROR[m] Re-run Maven using the [1m-X[m switch to enable full debug logging.
[[1;31mERROR[m] 
[[1;31mERROR[m] For more information about the errors and possible solutions, please read the following articles:
[[1;31mERROR[m] [1m[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

**Comment by vemonet** [comment]
Add `--no-match-user` to remove the `--user=1000:1000` added by CWL:

```
cwl-runner --no-match-user \
  --outdir /data/dqa-workspace/output \
  --tmp-outdir-prefix=/data/dqa-workspace/output/tmp-outdir/ \
  --tmpdir-prefix=/data/dqa-workspace/output/tmp-outdir/tmp- \
  workflows/workflow-dqa.cwl \
  support/config-cwl-dqa.yml
```

Sharing the `/usr/srv/myapp` folder causes it to be empty at runtime (so no bin)

**Comment by vemonet** [comment]
The issue is that because CWL forces to use a shared volume as workdir 
So running with maven fails because it doesn't find the project to execute (even when providing hardcoded path at runtime)

**Comment by vemonet** [comment]
I changed the directory right before doing the mvn exec: https://github.com/vemonet/RDFUnit/blob/master/bin/rdfunit#L20

But it still don't work

Giving this error:

```
No plugin found for prefix 'exec' in the current project and in the plugin groups 
[org.apache.maven.plugins, org.codehaus.mojo] available from the repositories 
[local (/root/.m2/repository), central (https://repo.maven.apache.org/maven2)] 
-> [1m[Help 1][m
```

Try it in the d2s-cwl-workflow git repo:
```
cwl-runner --no-match-user \                                                                                             
  --outdir /data/dqa-workspace/output \
  --tmp-outdir-prefix=/data/dqa-workspace/output/tmp-outdir/ \
  --tmpdir-prefix=/data/dqa-workspace/output/tmp-outdir/tmp- \
  workflows/workflow-dqa.cwl \
  support/config-cwl-dqa.yml
```

**Comment by vemonet** [comment]
I fixed RDFUnit to be packaged as a standalone jar in the RDFUnit Docker container. So using it from any path with any workdir set will work (available at https://hub.docker.com/repository/docker/umids/rdfunit )

What has been done: 
* added the shade plugin from the profile `cli-standalone` to the default build plugins in the pom.xml (using profiles was not clear) 
* rewriting the Dockerfile to build the standalone jar in a maven container before running it in a openjdk slim container
* use absolute path to run the jar in the Docker entrypoint

See [commits](https://github.com/vemonet/RDFUnit/commits/master):
* https://github.com/vemonet/RDFUnit/commit/cd57ffdc4b65cb2065f19f6f7e5691a8af3fe50d
* https://github.com/vemonet/RDFUnit/commit/447c9d4d588f3453e579043489b2dc2ee3932dff

**Comment by vemonet** [comment]
## Fairsharing not working

Facing errors when running fairsharing on page different than Chembl (https://fairsharing.org/biodbcore-000015/)

```bash
docker run -it --rm -v /data/dqa-workspace:/data/ umids/fairsharing-metrics https://fairsharing.org/FAIRsharing.29we0s
# Or STRING database page
docker run -it --rm -v /data/dqa-workspace:/data/ umids/fairsharing-metrics https://fairsharing.org/biodbcore-000340/
```

Here is an example of error message returned:

```
STRING
[]
['Mosquito Insecticide Resistance Ontology', 'Gene Ontology']
['Applies to: Data use = {Creative Commons Attribution 4.0 International (CC BY 4.0)}']
Traceback (most recent call last):
  File "/app/scrapper_metrics.py", line 99, in <module>
    dataset = catalog[str(metrics['url'])]
KeyError: 'https://fairsharing.org/biodbcore-000340/'
```

I tried it with about 6 URLs and all face an error
This one have issue with license:

```
docker run -it --rm -v /data/dqa-workspace:/data/ umids/fairsharing-metrics https://fairsharing.org/biodbcore-000699

Colorectal Cancer Atlas
[]
['Gene Ontology']
Traceback (most recent call last):
  File "/app/scrapper_metrics.py", line 61, in <module>
    licence = [lic_string]
NameError: name 'lic_string' is not defined
```


### Biosharing API

It seems like Biosharing are building an API (using Ruby on Rails): https://github.com/FAIRsharing/FAIRsharing-API

But this API has not been deployed for Fairsharing in production.
